### ISSUE TITLE
New features?

### ISSUE THREAD

**Issue by capitalist** [thoughtworks/byor-voting-web-app#1]
I appreciate that you've kept this app lean, only a license, but are there any plans to add more features?

I only ask because we're getting ready to build our own radar and a voting app with a bit more interface would be useful.

😜

**Comment by zigolab** [comment]
Thank for your suggestion of not following the "codeless" application movement... ;)
You'll find some code here soon, stay tuned!

In the meantime, if you want to join our internal beta program and try out the app for your BYOR session, reach me out on twitter (@zigolab). I'll be happy to support you in the process!
